pipeline:
  name: postgres-operator-examples
  identifier: postgresoperatorexamples
  projectIdentifier: Devops
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Indico
        repoName: postgres-operator-examples
        build: <+input>
  stages:
    - stage:
        name: devops-service
        identifier: push_containers
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cicdharness
              namespace: harness
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Background
                  name: dind
                  identifier: dind
                  spec:
                    connectorRef: account.dockerhubproxy
                    image: library/docker:dind
                    shell: Sh
                    privileged: true
                    entrypoint:
                      - "--storage-driver=vfs --tls=false"
              - step:
                  type: Run
                  name: push containers
                  identifier: push_containers
                  spec:
                    connectorRef: account.dockerhubproxy
                    image: library/docker:latest
                    shell: Sh
                    command: |-
                      sleep 30
                      docker --tls=false ps
                      apk update && apk add curl python3 py3-pip
                      pip3 install shyaml --break-system-packages
                      sh ./push_and_tag.sh
                    envVariables:
                      GCR_CREDENTIALS: <+secrets.getValue("account.hashicorpvault://vaulttoolsdrone/devops_gcr_credentials#data")>
                      CRUNCHY_PASSWORD: <+secrets.getValue("account.hashicorpvault://vaulttoolsdrone/crunchy_sa#password")>
                      CRUNCHY_USERNAME: <+secrets.getValue("account.hashicorpvault://vaulttoolsdrone/crunchy_sa#username")>
              - step:
                  type: Run
                  name: push helm charts
                  identifier: push_helm_charts
                  spec:
                    connectorRef: account.dockerhubproxy
                    image: alpine/helm
                    shell: Sh
                    command: |-
                      helm version
                      helm plugin install https://github.com/chartmuseum/helm-push
                      helm repo add --username $USERNAME --password $PASSWORD harbor https://harbor.devops.indico.io/chartrepo/indico-charts
                      sh upload_helm_charts.sh
          caching:
            enabled: false
            paths: []
