pipeline:
  name: postgres-operator-examples
  identifier: postgresoperatorexamples
  projectIdentifier: Devops
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Indico
        repoName: postgres-operator-examples
        build: <+input>
  stages:
    - stage:
        name: devops-service
        identifier: devops_service
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cicdharness
              namespace: harness
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: push helm charts
                  identifier: push_helm_charts
                  spec:
                    connectorRef: account.dockerhubproxy
                    image: alpine/helm
                    shell: Sh
                    command: |-
                      helm registry login --username $USERNAME --password $PASSWORD  https://harbor.devops.indico.io/indico-charts
                      sh upload_helm_charts.sh
                    privileged: true
                    envVariables:
                      HELM_EXPERIMENTAL_OCI: "1"
                      PASSWORD: <+secrets.getValue("account.hashicorpvault://vaulttoolsdrone/harbor-push-token#password")>
                      USERNAME: <+secrets.getValue("account.hashicorpvault://vaulttoolsdrone/harbor-push-token#username")>
                    resources:
                      limits:
                        memory: 6G
                        cpu: "1"
          caching:
            enabled: false
            paths: []
          sharedPaths:
            - /var/run
            - /var/lib/docker
